#!/usr/bin/env python3
"""
new_plugin.py — scaffold a new Amorph plugin (DSP + UI + manifest) from a spec.

The parameter list is the single source of truth; you write it once (a small JSON)
and this generates a compilable DSP skeleton, a working single-file UI (sliders,
light DOM, zoom-free fluid layout, full cleanup), and the .cmajorpatch manifest —
all wired to matching `param1..paramN` IDs. The generated code is designed to pass
cmajor_lint.py and ui_lint.py out of the box; fill in the DSP math and restyle the UI.

Spec (JSON):
    {
      "name": "My Drive", "id": "com.you.mydrive", "manufacturer": "You",
      "type": "fx",                 // fx | instrument | midi
      "width": 800, "height": 400,
      "params": [
        { "name": "Drive", "min": 0.0, "max": 1.0, "init": 0.3 },
        { "name": "Mix",   "min": 0.0, "max": 1.0, "init": 0.5, "unit": "%" }
      ]
    }

Usage:
    python3 new_plugin.py spec.json --out ./MyDrive
    python3 new_plugin.py --type fx --name "My Drive" --out ./MyDrive   # no params (edit later)
"""
from __future__ import annotations
import argparse
import json
import re
import sys
from pathlib import Path

TYPES = {"fx", "instrument", "midi"}


def ident(s: str, fallback: str) -> str:
    s = re.sub(r"\W+", "_", s).strip("_")
    if not s or s[0].isdigit():
        s = fallback
    return s


def pascal(s: str) -> str:
    return "".join(w.capitalize() for w in re.split(r"\W+", s) if w) or "Plugin"


def f(v) -> str:
    """Render a number as a Cmajor float literal."""
    return f"{float(v)}f"


def build_params(spec_params):
    """Return list of dicts with id, name, varname, min, max, init, unit."""
    out, used = [], set()
    for i, p in enumerate(spec_params, 1):
        name = p.get("name", f"Param {i}")
        var = "p_" + ident(name.lower(), f"p{i}")
        while var in used:
            var += "_"
        used.add(var)
        out.append({
            "id": f"param{i}", "name": name, "var": var,
            "min": p.get("min", 0.0), "max": p.get("max", 1.0),
            "init": p.get("init", 0.0), "unit": p.get("unit", ""),
        })
    return out


# --- DSP generation ----------------------------------------------------------

def gen_dsp(proc: str, ptype: str, params) -> str:
    decls, states, handlers = [], [], []
    for p in params:
        ann = f'[[ name: "{p["name"]}", min: {p["min"]}, max: {p["max"]}, init: {p["init"]}'
        if p["unit"]:
            ann += f', unit: "{p["unit"]}"'
        ann += " ]]"
        decls.append(f"    input event float {p['id']} {ann};")
        states.append(f"    float {p['var']} = {f(p['init'])};")
        handlers.append(
            f"    event {p['id']} (float v) {{ {p['var']} = clamp (v, {f(p['min'])}, {f(p['max'])}); }}")

    pblock = ""
    if params:
        pblock = "\n".join(decls) + "\n\n" + "\n".join(states) + "\n\n" + "\n".join(handlers) + "\n\n"

    if ptype == "fx":
        io = ("    input  stream float<2> in;\n"
              "    // input  stream float<2> scIn;   // optional sidechain (index 1)\n"
              "    output stream float<2> out;\n")
        body = ("        loop\n        {\n"
                "            var l = in[0];\n"
                "            var r = in[1];\n\n"
                "            // ---- your DSP here ----\n\n"
                "            out <- float<2> (l, r);\n"
                "            advance();\n        }\n")
    elif ptype == "instrument":
        io = ("    input  event std::midi::Message midiIn;\n"
              "    output stream float<2> out;\n")
        body = ("        loop\n        {\n"
                "            // ---- synth voices -> outL/outR ----\n"
                "            var outL = 0.0f;\n"
                "            var outR = 0.0f;\n\n"
                "            out <- float<2> (outL, outR);\n"
                "            advance();\n        }\n")
    else:  # midi
        io = ("    input  event std::midi::Message midiIn;\n"
              "    output event std::midi::Message midiOut;\n")
        body = "        loop { advance(); }\n"

    midi_handler = ""
    if ptype in ("instrument", "midi"):
        if ptype == "midi":
            midi_handler = ("\n    event midiIn (std::midi::Message msg)\n    {\n"
                            "        // ---- transform / generate MIDI; emit with midiOut <- ... ----\n"
                            "        midiOut <- msg;   // passthrough\n    }\n")
        else:
            midi_handler = ("\n    event midiIn (std::midi::Message msg)\n    {\n"
                            "        // ---- note on/off -> voice allocation ----\n    }\n")

    return (f"// {proc} — generated by new_plugin.py. Fill in the DSP.\n"
            f"processor {proc}\n{{\n{io}\n{pblock}{midi_handler}"
            f"    void main()\n    {{\n{body}    }}\n}}\n")


# --- manifest ----------------------------------------------------------------

def gen_manifest(spec, dsp_file, ui_file) -> str:
    is_instr = spec["type"] in ("instrument", "midi")
    m = {
        "CmajorVersion": 1,
        "ID": spec.get("id", "com.yourcompany." + ident(spec["name"].lower(), "plugin")),
        "version": "0.1.0",
        "name": spec["name"],
        "description": spec.get("description", ""),
        "category": "instrument" if is_instr else "effect",
        "manufacturer": spec.get("manufacturer", "Your Company"),
        "isInstrument": is_instr,
        "source": dsp_file,
        "view": {"src": ui_file, "width": spec.get("width", 800),
                 "height": spec.get("height", 400), "resizable": True},
    }
    return json.dumps(m, indent=2) + "\n"


# --- UI generation (single file, light DOM, official Amorph pattern) ---------

def gen_ui(tag: str, cls: str, spec, params) -> str:
    w, h = spec.get("width", 800), spec.get("height", 400)
    controls = "\n".join(
        f'      <div class="control" data-param="{p["id"]}" data-endpoint-id="{p["id"]}" '
        f'data-min="{p["min"]}" data-max="{p["max"]}" data-init="{p["init"]}" data-step="0">\n'
        f'        <input class="knob" type="range" min="{p["min"]}" max="{p["max"]}" '
        f'step="any" value="{p["init"]}">\n'
        f'        <span class="value-label">--</span>\n'
        f'        <span class="label">{p["name"]}</span>\n'
        f'      </div>'
        for p in params) or "      <!-- add controls -->"

    return f'''// {spec["name"]} UI — generated by new_plugin.py. Restyle freely (single file, no imports).
// WINDOW SIZE: {w}x{h}

class {cls} extends HTMLElement {{
  constructor(pc) {{ super(); this.pc = pc; this._controls = new Map(); this._listener = null; }}

  connectedCallback() {{
    this.innerHTML = this.getHTML();

    this.querySelectorAll(".control").forEach(node => {{
      const id  = node.dataset.param;
      const min = parseFloat(node.dataset.min ?? 0);
      const max = parseFloat(node.dataset.max ?? 1);
      const knob = node.querySelector(".knob");
      const label = node.querySelector(".value-label");
      const setValue = (v, notify) => {{
        v = Math.min(max, Math.max(min, v));
        knob.value = v;
        label.textContent = (Math.round(v * 1000) / 1000).toString();
        if (notify) this.pc.sendEventOrValue(id, v);
      }};
      knob.addEventListener("input", () => setValue(parseFloat(knob.value), true));
      this._controls.set(id, setValue);
      setValue(parseFloat(node.dataset.init ?? min), false);   // immediate paint
    }});

    // host -> UI (Amorph payload is one object: {{ endpointID, value }})
    this._listener = ({{ endpointID, value }}) => this._controls.get(endpointID)?.(value, false);
    this.pc.addAllParameterListener(this._listener);
    this._controls.forEach((_, id) => this.pc.requestParameterValue(id));
  }}

  disconnectedCallback() {{
    if (this._listener) this.pc.removeAllParameterListener(this._listener);
  }}

  getHTML() {{
    return `
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
  html, body {{ overflow: hidden; margin: 0; }}
  {tag} {{ display: block; width: 100%; height: 100%; overflow: hidden;
           background: #11141c; color: #cdd6e0; font-family: system-ui, sans-serif;
           user-select: none; -webkit-user-select: none; }}
  {tag} .panel {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
                  gap: 16px; padding: 24px; height: 100%; align-content: start; }}
  {tag} .control {{ display: flex; flex-direction: column; align-items: center; gap: 6px; }}
  {tag} .knob {{ width: 100%; }}
  {tag} .value-label {{ font-size: 13px; font-variant-numeric: tabular-nums; }}
  {tag} .label {{ font-size: 11px; text-transform: uppercase; letter-spacing: 1px; opacity: .7; }}
</style>
<div class="panel">
{controls}
</div>`;
  }}
}}

const TAG = "{tag}";
if (!customElements.get(TAG)) customElements.define(TAG, {cls});

export default function createPatchView(patchConnection) {{
  return new {cls}(patchConnection);
}}
'''


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Scaffold a new Amorph plugin.")
    ap.add_argument("spec", nargs="?", help="JSON spec file")
    ap.add_argument("--out", required=True, help="output directory")
    ap.add_argument("--type", choices=sorted(TYPES), help="override/define plugin type")
    ap.add_argument("--name", help="override/define plugin name")
    ap.add_argument("--force", action="store_true", help="overwrite existing files")
    args = ap.parse_args(argv)

    spec = json.loads(Path(args.spec).read_text()) if args.spec else {}
    if args.type:
        spec["type"] = args.type
    if args.name:
        spec["name"] = args.name
    spec.setdefault("name", "My Plugin")
    spec.setdefault("type", "fx")
    spec.setdefault("params", [])
    if spec["type"] not in TYPES:
        ap.error(f"type must be one of {sorted(TYPES)}")

    base = pascal(spec["name"])
    proc = base + "Processor"
    tag = re.sub(r"_+", "-", ident(spec["name"].lower(), "plugin")) + "-ui"
    cls = base + "UI"
    params = build_params(spec["params"])

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    files = {
        f"{base}DSP.cmajor": gen_dsp(proc, spec["type"], params),
        f"{base}UI.js": gen_ui(tag, cls, spec, params),
        f"{base}.cmajorpatch": gen_manifest(spec, f"{base}DSP.cmajor", f"{base}UI.js"),
    }
    for fn, content in files.items():
        path = out / fn
        if path.exists() and not args.force:
            print(f"! skip (exists): {path}  (use --force)")
            continue
        path.write_text(content, encoding="utf-8")
        print(f"✓ wrote {path}")
    print(f"\nScaffolded a '{spec['type']}' plugin with {len(params)} parameter(s) in {out}/")
    print("Next: fill in the DSP math, restyle the UI, then run preflight.py on the folder.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
